---
- name: Install sshfs
  apt:
    pkg:
    - sshfs

- name: Change the mount point on server1 to /mnt/storage
  replace:
    path: /etc/fstab
    after: '/mnt/'
    before: ' ext4'
    regexp: '^(.+)$'
    replace: 'storage'
  when: "'server1' in inventory_hostname"

- name: Create /mnt/storage if it does not exist on server2
  file:
    path: "/mnt/storage"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: "'server1' not in inventory_hostname"

- name: Add the sshfs mount of the volume to the fstab on server2
  lineinfile:
    dest: /etc/fstab
    regexp: "^sshfs"
    line: "sshfs#server1:/mnt/storage /mnt/storage fuse defaults,nonempty,allow_other,reconnect,_netdev,users,ServerAliveInterval=15,ServerAliveCountMax=3 0 0"
    state: present
  when: "'server1' not in inventory_hostname"

- name: Reboot
  reboot:

# TODO: volume did not seem mounted after first reboot, but was after additional reboot
- name: Reboot
  reboot:
  when: "'server1' not in inventory_hostname"

- name: Create /mnt/storage/test_server1
  file:
    path: "/mnt/storage/test_server1"
    state: file 
    owner: root
    group: root
    mode: 0644
  when: "'server1' in inventory_hostname"

- name: Create /mnt/storage/test_server2
  file:
    path: "/mnt/storage/test_server2"
    state: file 
    owner: root
    group: root
    mode: 0644
  when: "'server2' in inventory_hostname"
